# Journal Documents the retrieval of the sample data from archs4

### Original Author: Ling Thang - PATH GREU

notebook contains scipt to retrive data for 
* Tuberculosis (TB)

In [1]:
import archs4py as a4
import numpy as np
import pandas as pd

In [47]:
# downloads the latest version of the human counts file
# a4.download.counts("human", path = "GEO expression", type = "GENE_COUNTS", version = "latest")

In [2]:
file = "../data/human_gene_v2.5.h5"
GEOfile = "../data/geo_human_v1.h5"
a4.ls(file)

data
│ expression            uint32 | (67186, 888821)
meta
│ genes
│   biotype               str    | (67186,)
│   ensembl_gene          str    | (67186,)
│   symbol                str    | (67186,)
│ info
│   author                str    | ()
│   contact               str    | ()
│   creation-date         str    | ()
│   laboratory            str    | ()
│   version               str    | ()
│ samples
│   channel_count         str    | (888821,)
│   characteristics_ch1   str    | (888821,)
│   contact_address       str    | (888821,)
│   contact_city          str    | (888821,)
│   contact_country       str    | (888821,)
│   contact_institute     str    | (888821,)
│   contact_name          str    | (888821,)
│   contact_zip           str    | (888821,)
│   data_processing       str    | (888821,)
│   extract_protocol_ch1  str    | (888821,)
│   geo_accession         str    | (888821,)
│   instrument_model      str    | (888821,)
│   last_update_date      str    | (888821,)
│   library_selection     str    | (888821,)
│   library_source        str    | (888821,)
│   library_strategy      str    | (888821,)
│   molecule_ch1          str    | (888821,)
│   organism_ch1          str    | (888821,)
│   platform_id           str    | (888821,)
│   relation              str    | (888821,)
│   sample                str    | (888821,)
│   series_id             str    | (888821,)
│   singlecellprobability  float64 | (888821,)
│   source_name_ch1       str    | (888821,)
│   status                str    | (888821,)
│   submission_date       str    | (888821,)
│   taxid_ch1             str    | (888821,)
│   title                 str    | (888821,)
│   type                  str    | (888821,)

#### Helper Function

In [3]:
def split_and_clean_series_ids(series_list):
    """
    Split comma-separated series IDs and clean whitespace
    
    Parameters:
    series_list: List of strings that may contain comma-separated values
    
    Returns:
    numpy.ndarray: Array of cleaned, individual series IDs
    """
    split_list = []
    for item in series_list:
        split_list.extend([x.strip() for x in str(item).split(',')])
    
    return np.array(split_list)

### Pulmonary Tuberculosis (TB)

**ks mircroarrays data**

In [74]:
import pandas as pd
ks_micro_arrays = pd.read_csv(
    "../../integrative-drugrep-tb/data/metadata/refinebio_tb_datasets.tsv",
    sep="\t",
    usecols=[5]  # 7th column, 0-based index
)

In [ ]:
# drop missing and TRUE values
ks_micro_arrays = ks_micro_arrays.dropna()
ks_micro_arrays = ks_micro_arrays[ks_micro_arrays["accession_code"] != "TRUE"]

In [79]:
ks_micro_arrays = set(ks_micro_arrays['accession_code'])

**2024 TB data first query JAN**

In [3]:
# get sample meta data based on search term
PTB_meta = a4.meta.meta(file, "pulmonary tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
activeTB_meta = a4.meta.meta(file, "active tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
MTB_meta = a4.meta.meta(file, "MTB", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
LTB_meta = a4.meta.meta(file, "latent tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

100%|██████████| 6/6 [00:03<00:00,  1.95it/s]
100%|██████████| 6/6 [00:02<00:00,  2.08it/s]
100%|██████████| 6/6 [00:02<00:00,  2.15it/s]
100%|██████████| 6/6 [00:02<00:00,  2.00it/s]

In [4]:
import pandas as pd
TB_meta = pd.concat([PTB_meta, activeTB_meta, MTB_meta], ignore_index=True)
TB_meta

,geo_accession,series_id,characteristics_ch1,extract_protocol_ch1,source_name_ch1,title
0,GSM2732743,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-1
1,GSM2732744,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-2
2,GSM4810280,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H1
3,GSM4810281,GSE158767,"METABOLIC ACTIVITY: LOW METABOLIC ACTIVITY,GEN...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE L1
4,GSM4810282,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H2
...,...,...,...,...,...,...
2405,GSM8087252,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB UNINFECTED, 48 HOURS, 4"
2406,GSM8087253,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 1"
2407,GSM8087254,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 2"
2408,GSM8087255,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 3"
2409,GSM8087256,GSE256184,"CELL LINE: HEPG2,CELL TYPE: HEPTOCYTES,TREATME...",TOTAL RNA WAS ISOLATED USING MACHEREY-NAGEL (M...,HEPG2,"HEPG2 MTB INFECTED (48 HOUR POST INFECTION), 4"

In [5]:
MTB_meta2 = a4.meta.meta(file, "mycobacterium tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

lung_TB = a4.meta.meta(file, "lung tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

lung_TB2 = a4.meta.meta(file, "lung TB", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

100%|██████████| 6/6 [00:02<00:00,  2.06it/s]
100%|██████████| 6/6 [00:02<00:00,  2.06it/s]
100%|██████████| 6/6 [00:02<00:00,  2.06it/s]

In [8]:
import pandas as pd
TB_meta_updated= pd.concat([PTB_meta, activeTB_meta, MTB_meta, MTB_meta2, lung_TB, lung_TB2], ignore_index=True)
TB_meta_updated

,geo_accession,series_id,characteristics_ch1,extract_protocol_ch1,source_name_ch1,title
0,GSM2732743,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-1
1,GSM2732744,GSE102272,DISEASE STATUS: ACTIVE PULMONARY TUBERCULOSIS ...,TOTAL RNA WAS EXTRACTED FROM EACH SAMPLE OF PB...,"PERIPHERAL BLOOD MONONUCLEAR CELLS, APTB",TB-2
2,GSM4810280,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H1
3,GSM4810281,GSE158767,"METABOLIC ACTIVITY: LOW METABOLIC ACTIVITY,GEN...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE L1
4,GSM4810282,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H2
...,...,...,...,...,...,...
2579,GSM5573721,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),18P_TTNPB
2580,GSM5573723,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_ATRA
2581,GSM5573724,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_DMSO
2582,GSM5573725,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_EC23
2583,GSM5573726,GSE183912,"CELL TYPE: MACROPHAGES (MO-GMCSF),INFECTION ST...",RNA WAS EXTRACTED WITH BUFFER RLT (QIAGEN) AND...,HUMAN MACROPHAGES (MO-GMCSF),19A_TTNPB

In [11]:
TB_meta_list_updated = TB_meta_updated["series_id"].unique().tolist()
print(TB_meta_updated['series_id'].unique())
print(len(TB_meta_updated['series_id'].unique()))

['GSE102272' 'GSE158767' 'GSE190024' 'GSE84076' 'GSE94907' 'GSE148171'
 'GSE152218' 'GSE198557' 'GSE64179,GSE64183' 'GSE64182,GSE64183'
 'GSE100897' 'GSE102677,GSE102678' 'GSE103147' 'GSE107646' 'GSE112482'
 'GSE112483' 'GSE116405,GSE116412' 'GSE131415' 'GSE132048' 'GSE132283'
 'GSE138398' 'GSE141656' 'GSE143627' 'GSE148731' 'GSE162725' 'GSE164287'
 'GSE165708,GSE165709' 'GSE174566' 'GSE180480' 'GSE193777' 'GSE194017'
 'GSE199403' 'GSE207214' 'GSE211974,GSE211977' 'GSE216503' 'GSE223863'
 'GSE236154' 'GSE236156' 'GSE256184' 'GSE110564' 'GSE121049' 'GSE131590'
 'GSE143731' 'GSE183912']
44

In [12]:
TB_meta_split = []
for item in TB_meta_list_updated:
    TB_meta_split.extend([x.strip() for x in item.split(',')])
TB_meta_split = np.array(TB_meta_split)

print(TB_meta_split)
print(len(TB_meta_split))

# print the dup
print("Duplicates in TB_meta_split:")
duplicates = set(x for x in TB_meta_split if TB_meta_split.tolist().count(x) > 1)
print(duplicates)

# remove duplicates
TB_meta_split = np.unique(TB_meta_split)
print("After removing duplicates:")
print(len(TB_meta_split))

['GSE102272' 'GSE158767' 'GSE190024' 'GSE84076' 'GSE94907' 'GSE148171'
 'GSE152218' 'GSE198557' 'GSE64179' 'GSE64183' 'GSE64182' 'GSE64183'
 'GSE100897' 'GSE102677' 'GSE102678' 'GSE103147' 'GSE107646' 'GSE112482'
 'GSE112483' 'GSE116405' 'GSE116412' 'GSE131415' 'GSE132048' 'GSE132283'
 'GSE138398' 'GSE141656' 'GSE143627' 'GSE148731' 'GSE162725' 'GSE164287'
 'GSE165708' 'GSE165709' 'GSE174566' 'GSE180480' 'GSE193777' 'GSE194017'
 'GSE199403' 'GSE207214' 'GSE211974' 'GSE211977' 'GSE216503' 'GSE223863'
 'GSE236154' 'GSE236156' 'GSE256184' 'GSE110564' 'GSE121049' 'GSE131590'
 'GSE143731' 'GSE183912']
50
Duplicates in TB_meta_split:
{'GSE64183'}
After removing duplicates:
49

In [56]:
np.savetxt("../data/diseases/GSEs/TB_FULL_JUN.txt", sorted(TB_meta_split), fmt="%s")

In [13]:
TB_list_24 = TB_meta['series_id'].unique()
print(TB_meta['series_id'].unique())
print(TB_meta['series_id'].nunique())

['GSE102272' 'GSE158767' 'GSE190024' 'GSE84076' 'GSE94907' 'GSE148171'
 'GSE152218' 'GSE198557' 'GSE64179,GSE64183' 'GSE64182,GSE64183'
 'GSE100897' 'GSE102677,GSE102678' 'GSE103147' 'GSE107646' 'GSE112482'
 'GSE112483' 'GSE116405,GSE116412' 'GSE131415' 'GSE132048' 'GSE132283'
 'GSE138398' 'GSE141656' 'GSE143627' 'GSE148731' 'GSE162725' 'GSE164287'
 'GSE165708,GSE165709' 'GSE174566' 'GSE180480' 'GSE193777' 'GSE194017'
 'GSE199403' 'GSE207214' 'GSE211974,GSE211977' 'GSE216503' 'GSE223863'
 'GSE236154' 'GSE236156' 'GSE256184']
39

In [14]:
split_TB_list_24 = []
for item in TB_list_24:
    split_TB_list_24.extend([x.strip() for x in item.split(',')])
split_TB_list_24 = np.array(split_TB_list_24)

print(split_TB_list_24)
print(split_TB_list_24.size)

# contains dups 
split_TB_list_24 = np.unique(split_TB_list_24)
print(split_TB_list_24.size)

['GSE102272' 'GSE158767' 'GSE190024' 'GSE84076' 'GSE94907' 'GSE148171'
 'GSE152218' 'GSE198557' 'GSE64179' 'GSE64183' 'GSE64182' 'GSE64183'
 'GSE100897' 'GSE102677' 'GSE102678' 'GSE103147' 'GSE107646' 'GSE112482'
 'GSE112483' 'GSE116405' 'GSE116412' 'GSE131415' 'GSE132048' 'GSE132283'
 'GSE138398' 'GSE141656' 'GSE143627' 'GSE148731' 'GSE162725' 'GSE164287'
 'GSE165708' 'GSE165709' 'GSE174566' 'GSE180480' 'GSE193777' 'GSE194017'
 'GSE199403' 'GSE207214' 'GSE211974' 'GSE211977' 'GSE216503' 'GSE223863'
 'GSE236154' 'GSE236156' 'GSE256184']
45
44

In [25]:
split_TB_list_24 = set(split_TB_list_24)
TB_meta_split = set(TB_meta_split)

# print the size 
print(len(split_TB_list_24))
print(len(TB_meta_split))

# print the comparison

print("is the new list a superset of the old list? ", TB_meta_split >= split_TB_list_24) 
print("new studies not in old list: ", TB_meta_split - split_TB_list_24)

44
49
is the new list a superset of the old list?  True
new studies not in old list:  {'GSE143731', 'GSE183912', 'GSE110564', 'GSE131590', 'GSE121049'}

In [39]:
old_studies = pd.read_csv("../data/diseases/GSEs/TB_series_id.txt", sep="\t", header=None)
# convert to set
old_studies = set(old_studies[0].tolist())
print("currated studies in JAN: ", len(old_studies))

studies_processed = pd.read_csv("../data/LLM_context/report/ManuallyVerified/TB_man.tsv", sep="\t")
studies_processed = set(studies_processed['GSE_ID'].tolist())
print("studies processed: ", len(studies_processed))

currated studies in JAN:  33
studies processed:  24

In [49]:
studiestoadd_oldlist = old_studies - studies_processed
print("studies to add to old list:")
studiestoadd_oldlist

studies to add to old list:

{'GSE131415',
 'GSE132048',
 'GSE141656',
 'GSE162725',
 'GSE164287',
 'GSE180480',
 'GSE194017',
 'GSE216503',
 'GSE236154'}

In [54]:
all_studies_toadd = TB_meta_split - studies_processed
print("all studies to add: ", len(all_studies_toadd))
all_studies_toadd

all studies to add:  25

{'GSE102677',
 'GSE102678',
 'GSE110564',
 'GSE116405',
 'GSE116412',
 'GSE121049',
 'GSE131415',
 'GSE131590',
 'GSE132048',
 'GSE141656',
 'GSE143731',
 'GSE162725',
 'GSE164287',
 'GSE165708',
 'GSE165709',
 'GSE180480',
 'GSE183912',
 'GSE194017',
 'GSE211974',
 'GSE211977',
 'GSE216503',
 'GSE236154',
 'GSE64179',
 'GSE64182',
 'GSE64183'}

In [86]:
print(len(ks_micro_arrays))
print(len(TB_meta_split))

print(ks_micro_arrays & TB_meta_split)

28
49
set()

In [87]:
ks_micro_arrays

{'GSE102459',
 'GSE11199',
 'GSE119143',
 'GSE139871',
 'GSE16250',
 'GSE18794',
 'GSE19435',
 'GSE19439',
 'GSE19491',
 'GSE26305',
 'GSE29628',
 'GSE31348',
 'GSE34151',
 'GSE36238',
 'GSE39939',
 'GSE39940',
 'GSE39941',
 'GSE40553',
 'GSE42830',
 'GSE42834',
 'GSE45386',
 'GSE48237',
 'GSE57028',
 'GSE58411',
 'GSE63548',
 'GSE67589',
 'GSE70200',
 'GSE83456'}

In [18]:
# get sample meta data based on search term
PTB_GEO = a4.meta.meta(GEOfile, "pulmonary tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
activeTB_GEO = a4.meta.meta(GEOfile, "active tuberculosis", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

# get sample meta data based on search term
MTB_GEO = a4.meta.meta(GEOfile, "MTB", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])

100%|██████████| 6/6 [00:00<00:00,  6.21it/s]
100%|██████████| 6/6 [00:00<00:00,  6.05it/s]
100%|██████████| 6/6 [00:01<00:00,  5.79it/s]

In [ ]:
import pandas as pd
TB_GEO = pd.concat([PTB_GEO, activeTB_GEO, MTB_GEO], ignore_index=True)
TB_GEO

,geo_accession,series_id,characteristics_ch1,extract_protocol_ch1,source_name_ch1,title
0,GSM4810280,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H1
1,GSM4810281,GSE158767,"METABOLIC ACTIVITY: LOW METABOLIC ACTIVITY,GEN...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE L1
2,GSM4810282,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H2
3,GSM4810283,GSE158767,"METABOLIC ACTIVITY: LOW METABOLIC ACTIVITY,GEN...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE L2
4,GSM4810286,GSE158767,"METABOLIC ACTIVITY: HIGH METABOLIC ACTIVITY,GE...",TOTAL RNA OF EACH LUNG SAMPLE WAS EXTRACTED BY...,LUNG,LUNG TISSUE H4
...,...,...,...,...,...,...
936,GSM1565957,"GSE64179,GSE64183",CONDITION: MTB-INFECTED,TOTAL RNA WAS EXTRACTED FROM THE SAME SAMPLES ...,MONOCYTE-DERIVED DENDRITIC CELLS,DC_MTB_REP2 (RNA-SEQ)
937,GSM1565959,"GSE64179,GSE64183",CONDITION: MTB-INFECTED,TOTAL RNA WAS EXTRACTED FROM THE SAME SAMPLES ...,MONOCYTE-DERIVED DENDRITIC CELLS,DC_MTB_REP3 (RNA-SEQ)
938,GSM1565961,"GSE64179,GSE64183",CONDITION: MTB-INFECTED,TOTAL RNA WAS EXTRACTED FROM THE SAME SAMPLES ...,MONOCYTE-DERIVED DENDRITIC CELLS,DC_MTB_REP4 (RNA-SEQ)
939,GSM1565963,"GSE64179,GSE64183",CONDITION: MTB-INFECTED,TOTAL RNA WAS EXTRACTED FROM THE SAME SAMPLES ...,MONOCYTE-DERIVED DENDRITIC CELLS,DC_MTB_REP5 (RNA-SEQ)
940,GSM1565965,"GSE64179,GSE64183",CONDITION: MTB-INFECTED,TOTAL RNA WAS EXTRACTED FROM THE SAME SAMPLES ...,MONOCYTE-DERIVED DENDRITIC CELLS,DC_MTB_REP6 (RNA-SEQ)

In [53]:
TB_list_23 = TB_GEO['series_id'].unique()
print(TB_GEO['series_id'].unique())
print(TB_GEO['series_id'].nunique())

['GSE158767' 'GSE190024' 'GSE102272' 'GSE84076' 'GSE198557' 'GSE152218'
 'GSE148171' 'GSE94907' 'GSE141656' 'GSE143627' 'GSE116405,GSE116412'
 'GSE103147' 'GSE102677,GSE102678' 'GSE165708,GSE165709'
 'GSE64182,GSE64183' 'GSE131415' 'GSE132283' 'GSE112483' 'GSE148731'
 'GSE162725' 'GSE112482' 'GSE174566' 'GSE164287' 'GSE100897'
 'GSE64179,GSE64183']
25

In [69]:
import numpy as np

split_TB_list_23 = []
for item in TB_list_23:
    split_TB_list_23.extend([x.strip() for x in item.split(',')])
split_TB_list_23 = np.array(split_TB_list_23)

split_TB_list_23

array(['GSE158767', 'GSE190024', 'GSE102272', 'GSE84076', 'GSE198557',
       'GSE152218', 'GSE148171', 'GSE94907', 'GSE141656', 'GSE143627',
       'GSE116405', 'GSE116412', 'GSE103147', 'GSE102677', 'GSE102678',
       'GSE165708', 'GSE165709', 'GSE64182', 'GSE64183', 'GSE131415',
       'GSE132283', 'GSE112483', 'GSE148731', 'GSE162725', 'GSE112482',
       'GSE174566', 'GSE164287', 'GSE100897', 'GSE64179', 'GSE64183'],
      dtype='<U9')

In [70]:
split_TB_list_23.size

30

In [71]:
split_TB_list_23 = np.unique(split_TB_list_23)
print(split_TB_list_23.size)

29

In [72]:
ks_list = [
"GSE110564",
"GSE112482",
"GSE112483",
"GSE114033",
"GSE129270",
"GSE148171",
"GSE157657",
"GSE193777",
"GSE198557",
"GSE67427",
"GSE84076"
]

TB_list_24 = set(split_TB_list_24)
TB_list_23 = set(split_TB_list_23)
KS_list = set(ks_list)

In [90]:
print("studies in 24:", len(TB_list_24))
print("studies in 23:", len(TB_list_23))

# is every study in 23 also in 24?
print("is '24 a superset of '23?", TB_list_24 >= TB_list_23)

difference = TB_list_24 - TB_list_23
print("studies in 24 not in 23:", difference)
print("number of new studies in 24:", len(difference))

studies in 24: 44
studies in 23: 29
is '24 a superset of '23? True
studies in 24 not in 23: {'GSE194017', 'GSE211977', 'GSE216503', 'GSE211974', 'GSE132048', 'GSE236156', 'GSE180480', 'GSE193777', 'GSE236154', 'GSE107646', 'GSE199403', 'GSE256184', 'GSE138398', 'GSE223863', 'GSE207214'}
number of new studies in 24: 15

In [15]:
my_tb = pd.read_csv("../data/diseases/GSEs/TB_series_id.txt", header=None, names=["series_id"])
my_tb = my_tb['series_id'].tolist()

In [22]:
set(my_tb).intersection(set(ks_list))

{'GSE112482', 'GSE112483', 'GSE148171', 'GSE193777', 'GSE198557', 'GSE84076'}

In [92]:
print("elements in KS but not in GEO: \n", KS_list - TB_list_23) 
print("COUNT: \n", len(KS_list - TB_list_23))

print("\n elements in GEO but not in KS: \n", TB_list_23 - KS_list)
print("COUNT: \n", len(TB_list_23 - KS_list))

print("\n elements in both GEO and KS: \n", KS_list & TB_list_23)
print("COUNT: \n", len(KS_list & TB_list_23))

elements in KS but not in GEO:
 {'GSE157657', 'GSE114033', 'GSE129270', 'GSE193777', 'GSE110564', 'GSE67427'}
COUNT:
 6

 elements in GEO but not in KS:
 {'GSE165708', 'GSE116412', 'GSE102677', 'GSE158767', 'GSE165709', 'GSE141656', 'GSE100897', 'GSE116405', 'GSE152218', 'GSE64182', 'GSE102272', 'GSE164287', 'GSE174566', 'GSE64183', 'GSE131415', 'GSE190024', 'GSE64179', 'GSE148731', 'GSE103147', 'GSE162725', 'GSE143627', 'GSE94907', 'GSE102678', 'GSE132283'}
COUNT:
 24

 elements in both GEO and KS:
 {'GSE84076', 'GSE112482', 'GSE148171', 'GSE112483', 'GSE198557'}
COUNT:
 5

In [93]:
print("elements in KS but not in Archs4: \n", KS_list - TB_list_24) 
print("COUNT: \n", len(KS_list - TB_list_24))

print("\n elements in Archs4 but not in KS: \n", TB_list_24 - KS_list)
print("COUNT: \n", len(TB_list_24 - KS_list))

print("\n elements in both Archs4 and KS: \n", KS_list & TB_list_24)
print("COUNT: \n", len(KS_list & TB_list_24))

elements in KS but not in Archs4:
 {'GSE157657', 'GSE114033', 'GSE129270', 'GSE110564', 'GSE67427'}
COUNT:
 5

 elements in Archs4 but not in KS:
 {'GSE165708', 'GSE116412', 'GSE102677', 'GSE158767', 'GSE165709', 'GSE132048', 'GSE180480', 'GSE141656', 'GSE107646', 'GSE199403', 'GSE100897', 'GSE116405', 'GSE194017', 'GSE211977', 'GSE152218', 'GSE216503', 'GSE211974', 'GSE64182', 'GSE102272', 'GSE164287', 'GSE174566', 'GSE64183', 'GSE256184', 'GSE131415', 'GSE190024', 'GSE64179', 'GSE148731', 'GSE103147', 'GSE162725', 'GSE143627', 'GSE94907', 'GSE236156', 'GSE236154', 'GSE138398', 'GSE223863', 'GSE102678', 'GSE207214', 'GSE132283'}
COUNT:
 38

 elements in both Archs4 and KS:
 {'GSE84076', 'GSE112482', 'GSE148171', 'GSE193777', 'GSE112483', 'GSE198557'}
COUNT:
 6

# nontuberculous mycobacterial pulmonary disease

In [9]:
# get sample meta data based on search term
NTM_meta = a4.meta.meta(file, "NTM", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])
NTM_meta

100%|██████████| 6/6 [00:03<00:00,  1.92it/s]

,geo_accession,series_id,characteristics_ch1,extract_protocol_ch1,source_name_ch1,title
GSM1131553,GSM1131553,GSE46514,"CELL LINE: BJAB,CELL TYPE: EBV-NEGATIVE BURKIT...",1Ã10^8 CELLS WERE WASHED WITH PBS AND LYSED W...,BJAB CELLS_EMPTY_RISC-IP,3626AGO
GSM1131554,GSM1131554,GSE46514,"CELL LINE: BJAB,CELL TYPE: EBV-NEGATIVE BURKIT...",1Ã10^8 CELLS WERE WASHED WITH PBS AND LYSED W...,BJAB CELLS_BARTS_RISC-IP,3628AGO
GSM2095704,GSM2095704,GSE79463,"CELL LINE: HEPG2,CELL TYPE: HEPG2 CELLS ARE AD...",TOTAL RNA WAS ISOLATED FROM TISSUES WITH MIRVA...,HUMAN HEPG2 CELL LINE_SH CONTROL,CONTROL_I
GSM2095705,GSM2095705,GSE79463,"CELL LINE: HEPG2,CELL TYPE: HEPG2 CELLS ARE AD...",TOTAL RNA WAS ISOLATED FROM TISSUES WITH MIRVA...,HUMAN HEPG2 CELL LINE_SH CONTROL,CONTROL_2
GSM2095706,GSM2095706,GSE79463,"CELL LINE: HEPG2,CELL TYPE: HEPG2 CELLS ARE AD...",TOTAL RNA WAS ISOLATED FROM TISSUES WITH MIRVA...,HUMAN HEPG2 CELL LINE_SHNR2E3,SHNR2E3 KO_1
...,...,...,...,...,...,...
GSM7668335,GSM7668335,"GSE239582,GSE239583",TISSUE: FALLOPIAN TUBE,ISOLATED WÎ²A OR NON-WÎ²A CELLS WERE SORTED IN...,FALLOPIAN TUBE,BATCH1_PATIENT11600-15149_DH10_2
GSM7668336,GSM7668336,"GSE239582,GSE239583",TISSUE: FALLOPIAN TUBE,ISOLATED WÎ²A OR NON-WÎ²A CELLS WERE SORTED IN...,FALLOPIAN TUBE,BATCH1_PATIENT11600-15149_DH11_1
GSM7668337,GSM7668337,"GSE239582,GSE239583",TISSUE: FALLOPIAN TUBE,ISOLATED WÎ²A OR NON-WÎ²A CELLS WERE SORTED IN...,FALLOPIAN TUBE,BATCH1_PATIENT11600-15149_DH11_2
GSM7668338,GSM7668338,"GSE239582,GSE239583",TISSUE: FALLOPIAN TUBE,ISOLATED WÎ²A OR NON-WÎ²A CELLS WERE SORTED IN...,FALLOPIAN TUBE,BATCH1_PATIENT11600-15149_DH12_1
GSM7668339,GSM7668339,"GSE239582,GSE239583",TISSUE: FALLOPIAN TUBE,ISOLATED WÎ²A OR NON-WÎ²A CELLS WERE SORTED IN...,FALLOPIAN TUBE,BATCH1_PATIENT11600-15149_DH12_2

In [12]:
# get sample meta data based on search term
NTMPD_meta = a4.meta.meta(file, "NTM-PD", meta_fields=["geo_accession","series_id","characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"])
NTMPD_meta

100%|██████████| 6/6 [00:02<00:00,  2.01it/s]

Empty DataFrame
Columns: [geo_accession, series_id, characteristics_ch1, extract_protocol_ch1, source_name_ch1, title]
Index: []